[project]
name = "matcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faiss-cpu>=1.11.0.post1",
    "httpx>=0.28.1",
    "imagehash>=4.3.2",
    "numpy>=2.3.2",
    "tqdm>=4.67.1",
]
