[project]
name = "third-eye"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["uvicorn>=0.35.0"]

[tool.uv.workspace]
members = ["extractor", "scrycache", "matcher", "tiny-embed-server"]
