[project]
name = "extractor"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = ["numpy>=2.3.2", "opencv-python>=4.11.0.86"]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
